### PR TITLE
Add playwright test

### PR DESCRIPTION
**Pull request by avirgulto**
Updated playwright testing to pass for use case 1. 

_Pull down request generator add-playwright branch which just add a testid flag to grab the dropdowns._ 
-- That PR got merged in so just test it out with dev of request-generator

To test, ensure playwright is installed. (https://playwright.dev/docs/intro) 

I run the test in the UI view so I can see how things are running, from command line run: 
npx playwright test --ui 
Screenshot 2023-10-13 at 10 19 01 AM

Then under uc1 test you can hit the run button and see it run in the main window.

### CODE REVIEW

**Review by zacharyrobin — CHANGES_REQUESTED** [review]
Run into error trying to find the medication in the drop down:
 on line 
  45 - `await patientBox.getByTestId("dropdown-box").first().click();`
                                                                                                                          
```
locator.click: Page closed
=========================== logs ===========================
waiting for locator('.patient-selection-box').filter({ hasText: 'Jon Snow' }).getByTestId('dropdown-box').first()
============================================================
```

Its looking for the dropdown to select 'jon snow' in a drop down list but I think we have restructured. I think it need to be looking for it in the `<div class="patient-box">` ? not sure but this may be where its getting snagged.

**Comment by zacharyrobin** [comment]
initial prescriber login needed. This may be due to EHR changes, but the playwrite test gets stuck initially on the login of the prescriber. erro: 
```
Timed out 5000ms waiting for expect(locator).toHaveTitle(expected)

Locator: locator(':root')
Expected pattern: /EHR/
Received string:  "Sign in to ClientFhirServer"
```


Screenshot 2023-11-28 at 10 40 48 AM

**Comment by zacharyrobin** [comment]
Im able to get all the way to prescriber enrollment and then it gets stuck, I reset everything and then it gets to only viewing the pims the first time? This may be issues with playwright  itself being buggy since its inconsistent I dont think its your test. I'm going to reset everything and try again.

**Review by smalho01 — APPROVED** [review]

**Review by zacharyrobin — APPROVED** [review]
Timing changes fixed it. Was able to successfully run through the test.

**Pull request merged**
